version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(github-actions)"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(pub)"
