name: On branch updated
on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          architecture: x64
      - run: flutter --version
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Test
        run: flutter test --verbose
      - name: Test Verbose
        if: success() || failure()
        run: flutter test --verbose
